name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: iraizo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_introduction: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, js
          plugin_languages_skipped: raizo.dev
          plugin_languages_threshold: 2% 
          plugin_activity: yes
          plugin_activity_limit: 5  
          plugin_activity_days: 14  
          plugin_activity_filter: all 
